server:
  http_listen_port: 9090
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://glc_eyJvIjoiOTAyMjAxIiwibiI6InN0YWNrLTY5NDU2NC1obC1kZWltb3Nsb2tpIiwiayI6IldWbkM2MFlYNTYwQzJ1S0owOEEwUUIyQyIsIm0iOnsiciI6InByb2QtZ2Itc291dGgtMCJ9fQ==@logs-prod-008.grafana.net/loki/api/v1/push

scrape_configs:


  - job_name: docker
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        host: localhost
        __path__: /var/lib/docker/containers/*/*.log
